//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fumble
    {
        public int fumbles_Id { get; set; }
        public string no_ { get; set; }
        public string lost { get; set; }
        public string playerGame_Id { get; set; }
    
        public virtual PlayerGame PlayerGame { get; set; }
    }
}
