//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linescore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Linescore()
        {
            this.Lineprds = new HashSet<Lineprd>();
        }
    
        public int linescore_Id { get; set; }
        public decimal prds { get; set; }
        public string line { get; set; }
        public decimal score { get; set; }
        public int teamGame_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lineprd> Lineprds { get; set; }
        public virtual TeamGame TeamGame { get; set; }
    }
}
