//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineprd
    {
        public int lineprd_Id { get; set; }
        public decimal prd { get; set; }
        public decimal score { get; set; }
        public int linescore_Id { get; set; }
    
        public virtual Linescore Linescore { get; set; }
    }
}
