//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LongPlay
    {
        public int longplay_Id { get; set; }
        public string thresh { get; set; }
        public string vh { get; set; }
        public string team { get; set; }
        public Nullable<decimal> yds { get; set; }
        public string play { get; set; }
        public string players { get; set; }
        public string td { get; set; }
        public string Game_Id { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
