//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UAAthleticsEntities : DbContext
    {
        public UAAthleticsEntities()
            : base("name=UAAthleticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Defense> Defenses { get; set; }
        public virtual DbSet<Fg> Fgs { get; set; }
        public virtual DbSet<Fumble> Fumbles { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Ir> Irs { get; set; }
        public virtual DbSet<Ko> Koes { get; set; }
        public virtual DbSet<Kr> Krs { get; set; }
        public virtual DbSet<Lineprd> Lineprds { get; set; }
        public virtual DbSet<Linescore> Linescores { get; set; }
        public virtual DbSet<LongPlay> LongPlays { get; set; }
        public virtual DbSet<Official> Officials { get; set; }
        public virtual DbSet<Pass> Passes { get; set; }
        public virtual DbSet<Pat> Pats { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerGame> PlayerGames { get; set; }
        public virtual DbSet<Pr> Prs { get; set; }
        public virtual DbSet<Punt> Punts { get; set; }
        public virtual DbSet<QtrSummary> QtrSummaries { get; set; }
        public virtual DbSet<Rcv> Rcvs { get; set; }
        public virtual DbSet<Rush> Rushes { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<Scoring> Scorings { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamGame> TeamGames { get; set; }
    }
}
