//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pat
    {
        public int pat_Id { get; set; }
        public Nullable<decimal> kickAtt { get; set; }
        public Nullable<decimal> kickMade { get; set; }
        public Nullable<decimal> passAtt { get; set; }
        public Nullable<decimal> passMade { get; set; }
        public Nullable<decimal> rushAtt { get; set; }
        public Nullable<decimal> rushMade { get; set; }
        public string playerGame_Id { get; set; }
    
        public virtual PlayerGame PlayerGame { get; set; }
    }
}
