//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punt
    {
        public int punt_Id { get; set; }
        public decimal no_ { get; set; }
        public decimal yds_ { get; set; }
        public decimal long_ { get; set; }
        public decimal blkd_ { get; set; }
        public decimal tb { get; set; }
        public decimal fc { get; set; }
        public decimal plus50 { get; set; }
        public decimal inside20 { get; set; }
        public string playerGame_Id { get; set; }
    
        public virtual PlayerGame PlayerGame { get; set; }
    }
}
