//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int scores_Id { get; set; }
        public string vh { get; set; }
        public string team { get; set; }
        public string qtr { get; set; }
        public string clock { get; set; }
        public string type_ { get; set; }
        public string how { get; set; }
        public Nullable<decimal> yds { get; set; }
        public string scorer { get; set; }
        public string passer { get; set; }
        public string patBy { get; set; }
        public string patType { get; set; }
        public string patRes { get; set; }
        public Nullable<decimal> plays { get; set; }
        public Nullable<decimal> drive { get; set; }
        public string top_ { get; set; }
        public string vScore { get; set; }
        public string hScore { get; set; }
        public string driveIndex { get; set; }
        public string game_Id { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
