//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scoring
    {
        public int scoring_Id { get; set; }
        public Nullable<decimal> td { get; set; }
        public Nullable<decimal> fg { get; set; }
        public Nullable<decimal> kick { get; set; }
        public Nullable<decimal> rush { get; set; }
        public Nullable<decimal> rcv { get; set; }
        public Nullable<decimal> saf { get; set; }
        public string playerGame_Id { get; set; }
    
        public virtual PlayerGame PlayerGame { get; set; }
    }
}
