//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamGame()
        {
            this.Linescores = new HashSet<Linescore>();
            this.QtrSummaries = new HashSet<QtrSummary>();
        }
    
        public int teamGame_Id { get; set; }
        public string teamName { get; set; }
        public string vh { get; set; }
        public string code { get; set; }
        public string record { get; set; }
        public string confRecord { get; set; }
        public string abb { get; set; }
        public string rank_ { get; set; }
        public Nullable<decimal> totOffPlays { get; set; }
        public Nullable<decimal> totOffYards { get; set; }
        public Nullable<decimal> totOffAvg { get; set; }
        public Nullable<decimal> firstDownNo { get; set; }
        public Nullable<decimal> firstDownRush { get; set; }
        public Nullable<decimal> firstDownPass { get; set; }
        public Nullable<decimal> firstDownPen { get; set; }
        public Nullable<decimal> penaltyNo { get; set; }
        public Nullable<decimal> penaltyYds { get; set; }
        public Nullable<decimal> thirdConv { get; set; }
        public Nullable<decimal> thirdAtt { get; set; }
        public Nullable<decimal> fourthConv { get; set; }
        public Nullable<decimal> fourthAtt { get; set; }
        public Nullable<decimal> fumbles { get; set; }
        public Nullable<decimal> fumblesLost { get; set; }
        public Nullable<decimal> miscYds { get; set; }
        public string timeOfPoss { get; set; }
        public Nullable<decimal> onsideAtt { get; set; }
        public Nullable<decimal> onsideMade { get; set; }
        public Nullable<decimal> pointsOffTurnovers { get; set; }
        public Nullable<decimal> rzAtt { get; set; }
        public Nullable<decimal> rzScores { get; set; }
        public Nullable<decimal> rzPoints { get; set; }
        public Nullable<decimal> rzTdRush { get; set; }
        public Nullable<decimal> rzTdPass { get; set; }
        public Nullable<decimal> rzFgMade { get; set; }
        public Nullable<decimal> rzEndFga { get; set; }
        public Nullable<decimal> rzEndDowns { get; set; }
        public Nullable<decimal> rzEndInt { get; set; }
        public Nullable<decimal> rzEndFumb { get; set; }
        public Nullable<decimal> rzEndHalf { get; set; }
        public Nullable<decimal> rzEndGame { get; set; }
        public Nullable<decimal> rushAtt { get; set; }
        public Nullable<decimal> rushYds { get; set; }
        public Nullable<decimal> rushGain { get; set; }
        public Nullable<decimal> rushLoss { get; set; }
        public Nullable<decimal> rushTd { get; set; }
        public Nullable<decimal> rushLong { get; set; }
        public Nullable<decimal> passComp { get; set; }
        public Nullable<decimal> passAtt { get; set; }
        public Nullable<decimal> passInt { get; set; }
        public Nullable<decimal> passYds { get; set; }
        public Nullable<decimal> passTd { get; set; }
        public Nullable<decimal> passLong { get; set; }
        public Nullable<decimal> passSacks { get; set; }
        public Nullable<decimal> passSackYds { get; set; }
        public Nullable<decimal> rcvNo { get; set; }
        public Nullable<decimal> rcvYds { get; set; }
        public Nullable<decimal> rcvTd { get; set; }
        public Nullable<decimal> rcvLong { get; set; }
        public Nullable<decimal> puntNo { get; set; }
        public Nullable<decimal> puntYds { get; set; }
        public Nullable<decimal> puntLong { get; set; }
        public Nullable<decimal> puntBlkd { get; set; }
        public Nullable<decimal> puntTb { get; set; }
        public Nullable<decimal> puntFc { get; set; }
        public Nullable<decimal> puntPlus50 { get; set; }
        public Nullable<decimal> puntInside20 { get; set; }
        public Nullable<decimal> koNo { get; set; }
        public Nullable<decimal> koYds { get; set; }
        public Nullable<decimal> koOb { get; set; }
        public Nullable<decimal> koTb { get; set; }
        public Nullable<decimal> fgAtt { get; set; }
        public Nullable<decimal> fgLong { get; set; }
        public Nullable<decimal> fgBlkd { get; set; }
        public Nullable<decimal> fgMade { get; set; }
        public Nullable<decimal> patAtt { get; set; }
        public Nullable<decimal> patMade { get; set; }
        public Nullable<decimal> patKickAtt { get; set; }
        public Nullable<decimal> patKickMade { get; set; }
        public Nullable<decimal> patPassAtt { get; set; }
        public Nullable<decimal> patPassMade { get; set; }
        public Nullable<decimal> patRushAtt { get; set; }
        public Nullable<decimal> patRushMade { get; set; }
        public Nullable<decimal> krTd { get; set; }
        public Nullable<decimal> krYds { get; set; }
        public Nullable<decimal> krNo { get; set; }
        public Nullable<decimal> krLong { get; set; }
        public Nullable<decimal> prTd { get; set; }
        public Nullable<decimal> prYds { get; set; }
        public Nullable<decimal> prNo { get; set; }
        public Nullable<decimal> prLong { get; set; }
        public Nullable<decimal> irTd { get; set; }
        public Nullable<decimal> irYds { get; set; }
        public Nullable<decimal> irNo { get; set; }
        public Nullable<decimal> irLong { get; set; }
        public Nullable<decimal> defTackUA { get; set; }
        public Nullable<decimal> defTackA { get; set; }
        public Nullable<decimal> defTflUA { get; set; }
        public Nullable<decimal> defTflA { get; set; }
        public Nullable<decimal> defTflYards { get; set; }
        public Nullable<decimal> defSacks { get; set; }
        public Nullable<decimal> defSackYds { get; set; }
        public Nullable<decimal> defBrup { get; set; }
        public Nullable<decimal> defQbh { get; set; }
        public Nullable<decimal> defInts { get; set; }
        public Nullable<decimal> defIntYds { get; set; }
        public Nullable<decimal> defFF { get; set; }
        public Nullable<decimal> defFR { get; set; }
        public Nullable<decimal> defFRYards { get; set; }
        public Nullable<decimal> scoringTD { get; set; }
        public Nullable<decimal> scoringFG { get; set; }
        public Nullable<decimal> scoringPatKick { get; set; }
        public Nullable<decimal> scoringPatRush { get; set; }
        public Nullable<decimal> scoringPatRcv { get; set; }
        public Nullable<decimal> scoringSaf { get; set; }
        public int team_Id { get; set; }
        public string game_Id { get; set; }
        public Nullable<decimal> defBlkd { get; set; }
    
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Linescore> Linescores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QtrSummary> QtrSummaries { get; set; }
        public virtual Team Team { get; set; }
    }
}
